/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PKSccpzW8fB
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardContent } from "@/components/ui/card";
import { useSession } from "next-auth/react";
import Link from "next/link";
import Nav from "../components/Nav";
import {
  BarChartIcon,
  BriefcaseIcon,
  CalendarIcon,
  DollarSignIcon,
  PiggyBankIcon,
  TrendingUpIcon,
  WalletIcon,
} from "../lib/svgs";

export function Outline() {
  const sessionData = useSession().data;

  return (
    <div className="grid min-h-screen w-screen grid-cols-1 bg-gradient-to-br from-slate-50 to-indigo-50 md:grid-cols-[1fr_300px]">
      <main className="ml-80 flex w-full flex-col items-start justify-center gap-8 pr-80">
        <div className="flex w-full flex-col items-start justify-center gap-4">
          <p className="text-3xl text-gray-700 dark:text-gray-400">
            Hey, {sessionData?.user?.name?.split(" ")[0]}!
          </p>
          <div className="text-8xl font-bold text-gray-900 dark:text-gray-50">
            $89,432
          </div>
          <p className="text-gray-500 dark:text-gray-400">Current Net Worth</p>
        </div>
        <div className="grid w-full grid-cols-1 gap-4 md:grid-cols-3">
          <Card className="col-span-2 bg-gradient-to-br from-white to-slate-50 pt-4 transition hover:scale-105 hover:shadow-md md:col-span-2">
            <Link href="/expenses">
              <CardContent className="flex flex-col items-start justify-center gap-4">
                <div className="flex w-full items-center justify-between">
                  <div>
                    <WalletIcon className="h-8 w-8 text-primary" />
                    <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                      $12,345
                    </div>
                    <p className="text-gray-500 dark:text-gray-400">Expenses</p>
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <p className="text-gray-500 dark:text-gray-400">Rent</p>
                      <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                        $1,500
                      </div>
                    </div>
                    <div>
                      <p className="text-gray-500 dark:text-gray-400">Auto</p>
                      <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                        $350
                      </div>
                    </div>
                    <div>
                      <p className="text-gray-500 dark:text-gray-400">
                        Utilities
                      </p>
                      <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                        $200
                      </div>
                    </div>
                    <div>
                      <p className="text-gray-500 dark:text-gray-400">
                        Groceries
                      </p>
                      <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                        $500
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Link>
          </Card>
          <Card className="col-span-1 bg-gradient-to-br from-white to-slate-50 pt-4 transition hover:scale-105 hover:shadow-md md:col-span-1">
            <Link href="#">
              <CardContent className="flex h-full flex-col items-center justify-center gap-4">
                <div className="flex w-full items-center justify-between">
                  <div>
                    <PiggyBankIcon className="h-8 w-8 text-primary" />
                    <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                      $8,901
                    </div>
                    <p className="text-gray-500 dark:text-gray-400">Savings</p>
                  </div>
                </div>
              </CardContent>
            </Link>
          </Card>
          <Card className="col-span-1 bg-gradient-to-br from-white to-slate-50 pt-4 transition hover:scale-105 hover:shadow-md md:col-span-1">
            <Link href="#">
              <CardContent className="flex h-full flex-col items-center justify-center gap-4">
                <div className="flex w-full items-center justify-between">
                  <div>
                    <TrendingUpIcon className="h-8 w-8 text-primary" />
                    <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                      $45,678
                    </div>
                    <p className="text-gray-500 dark:text-gray-400">
                      Investments
                    </p>
                  </div>
                </div>
              </CardContent>
            </Link>
          </Card>
          <Card className="col-span-2 bg-gradient-to-br from-white to-slate-50 pt-4 transition hover:scale-105 hover:shadow-md md:col-span-2">
            <Link href="#">
              <CardContent className="flex flex-col items-start justify-center gap-4">
                <div className="flex w-full items-center justify-between">
                  <div>
                    <CalendarIcon className="h-8 w-8 text-primary" />
                    <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                      $2,345
                    </div>
                    <p className="text-gray-500 dark:text-gray-400">Bills</p>
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <p className="text-gray-500 dark:text-gray-400">
                        Electricity
                      </p>
                      <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                        $150
                      </div>
                    </div>
                    <div>
                      <p className="text-gray-500 dark:text-gray-400">Water</p>
                      <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                        $75
                      </div>
                    </div>
                    <div>
                      <p className="text-gray-500 dark:text-gray-400">
                        Internet
                      </p>
                      <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                        $100
                      </div>
                    </div>
                    <div>
                      <p className="text-gray-500 dark:text-gray-400">Phone</p>
                      <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                        $75
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Link>
          </Card>
          <Card className="col-span-3 bg-gradient-to-br from-white to-slate-50 pt-4 transition hover:scale-105 hover:shadow-md md:col-span-3">
            <Link href="#">
              <CardContent className="flex flex-col items-start justify-center gap-4">
                <div className="flex w-full items-center justify-between">
                  <div>
                    <BarChartIcon className="h-8 w-8 text-primary" />
                    <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                      $3,456
                    </div>
                    <p className="text-gray-500 dark:text-gray-400">
                      Budgeting
                    </p>
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <p className="text-gray-500 dark:text-gray-400">Food</p>
                      <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                        $1,000
                      </div>
                    </div>
                    <div>
                      <p className="text-gray-500 dark:text-gray-400">
                        Entertainment
                      </p>
                      <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                        $500
                      </div>
                    </div>
                    <div>
                      <p className="text-gray-500 dark:text-gray-400">Misc</p>
                      <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                        $500
                      </div>
                    </div>
                    <div>
                      <p className="text-gray-500 dark:text-gray-400">
                        Savings
                      </p>
                      <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                        $1,456
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Link>
          </Card>
          <Card className="col-span-2 bg-gradient-to-br from-white to-slate-50 pt-4 transition hover:scale-105 hover:shadow-md md:col-span-2">
            <Link href="#">
              <CardContent className="flex flex-col items-start justify-center gap-4">
                <div className="flex w-full items-center justify-between">
                  <div>
                    <DollarSignIcon className="h-8 w-8 text-primary" />
                    <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                      $7,890
                    </div>
                    <p className="text-gray-500 dark:text-gray-400">Income</p>
                  </div>
                  <div className="gap-4">
                    <div>
                      <p className="text-gray-500 dark:text-gray-400">
                        Monthly
                      </p>
                      <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                        $6,000
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Link>
          </Card>
          <Card className="col-span-1 bg-gradient-to-br from-white to-slate-50 pt-4 transition hover:scale-105 hover:shadow-md md:col-span-1">
            <Link href="#">
              <CardContent className="flex flex-col items-start justify-center gap-4">
                <div className="flex w-full items-center justify-between">
                  <div>
                    <BriefcaseIcon className="h-8 w-8 text-primary" />
                    <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                      $23,456
                    </div>
                    <p className="text-gray-500 dark:text-gray-400">Assets</p>
                  </div>
                </div>
              </CardContent>
            </Link>
          </Card>
          <Card className="col-span-3 bg-gradient-to-br from-white to-slate-50 pt-4 transition hover:scale-105 hover:shadow-md md:col-span-3">
            <Link href="#">
              <CardContent className="flex flex-col items-start justify-center gap-4">
                <div className="flex w-full items-center justify-between">
                  <div>
                    <BriefcaseIcon className="h-8 w-8 text-primary" />
                    <div className="text-2xl font-bold text-gray-900 dark:text-gray-50">
                      $10,000
                    </div>
                    <p className="text-gray-500 dark:text-gray-400">Goals</p>
                  </div>
                </div>
              </CardContent>
            </Link>
          </Card>
        </div>
      </main>
      <Nav />
    </div>
  );
}
